### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by mehmetcanfarsak** [Ak4zh/Caprover-API#1]
First of all thanks a lot for this great repo. You have made a great job. 
I think adding backup download should be added.
It is on "settings->create backup " in  caprover  ui 

Thanks again

**Comment by mehmetcanfarsak** [comment]
?

**Comment by mehmetcanfarsak** [comment]
@Ak4zh

**Comment by Ak4zh** [comment]
#2d7d0e4dac8ce324c22a4513edc84f827868439f
